### ISSUE TITLE
The online doc should match the _stable_ version of silex

### ISSUE THREAD

**Issue by RoPP** [silexphp/Silex#1350] opened 2016-05-11 16:48 UTC
I've just lost few hours to configure swiftmailer with some unavailable options, this is not nice.

Could you, at least, indicate the version to which the doc refer ?

**Comment by ragboyjr** [comment] 2016-05-11 17:11
Which version of silex and swift mailer are you trying to use?

**Comment by RoPP** [comment] 2016-05-11 17:24
I'm using silex v1.3.5 and the swiftmailer.delivery_addresses option does not exist in https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SwiftmailerServiceProvider.php (but it does in https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/SwiftmailerServiceProvider.php).

**Comment by SpacePossum** [comment] 2016-05-11 18:26
which docs are you reading?
(http://silex.sensiolabs.org/doc/providers/swiftmailer.html `delivery_addresses` is not listed there)

**Comment by RoPP** [comment] 2016-05-12 07:24
I'm reading the same page, but I also uses uBlock Origin and it seem that part of the doc is removed by some js (which is blocked in my case) :(

**Comment by jdreesen** [comment] 2016-05-12 08:04
This is funny. I can confirm this. With uBlock Origin enabled I can see the `delivery_addresses` part and when disabled it's gone.

**Comment by mathroc** [comment] 2016-05-12 09:47
indeed it seems that's the doc from the master branch here (but uBlock makes no difference here, I always have the `delivery_addresses` part). @fabpot is it intended ? or maybe because of the incoming v2 release ?

**Comment by fabpot** [comment] 2016-05-16 18:58
Closing as a new version of the docs with both 1.3 and master are going to be deployed later today.

**Closed by fabpot** 2016-05-16 18:58 UTC
