### ISSUE TITLE
missing fonts from the e-pub format documentation

### ISSUE THREAD

**Issue by horpa** [silexphp/Silex#577] opened 2013-01-10 12:27 UTC
As you know the e-pub file is a zip, that contains a lot of html, css and other files.
In the generated package there is a file called "epub.css" it says:

@font-face {
    font-family: "my-sans-serif";
    font-style: normal;
    font-weight: normal;
    src: url("liberation/LiberationSansNarrow-Regular.ttf");
}

but there's no ttf font in the package. So those files are missing.

**Comment by desarrolla2** [comment] 2015-09-03 10:06
I think it's not a bug of silex, there is a problem with the sphinx's theme, which is not in this repository so it can be closed.

**Comment by fabpot** [comment] 2015-09-15 06:46
Closing as we will soon change the way we generate docs

**Closed by fabpot** 2015-09-15 06:46 UTC
Labels: doc
