### ISSUE TITLE
Authentication does not work with HHVM - user data is not persisted

### ISSUE THREAD

**Issue by maurocolella** [silexphp/Silex#992] opened 2014-07-24 12:48 UTC
The problem description is available from:
http://stackoverflow.com/questions/24933045/silex-framework-user-is-always-anonymous

System: Ubuntu 14.04
Architecture: amd64
HHVM Version: 3.2.0~trusty
Silex Version: ~1.1

Not tested with 1.2.

**Comment by stephenmelrose** [comment] 2015-02-18 16:31
Also having this exact problem. Tried native sessions and redis sessions.

silex/silex v1.2.3
symfony/security v2.6.4

**Comment by stephenmelrose** [comment] 2015-02-18 17:26
On review, I think I'm having a similar problem, but probably caused by the same root issue. See the below logs,

    [2015-02-18 17:15:00] myapp.INFO: Matched route "GET_login" (parameters: "_controller": "MyApp\Controller\LoginController::homeAction", "_route": "GET_login") [] []
    [2015-02-18 17:15:00] myapp.INFO: > GET /login [] []
    [2015-02-18 17:15:00] myapp.INFO: < 200 [] []
    [2015-02-18 17:15:00] myapp.DEBUG: array (   0 => '.',   1 => '..',   2 => 'perf-7.map',   3 => 'sess_a806e2acddb4dc5a69753d0cd961d3f2', ) [] []

    [2015-02-18 17:15:25] myapp.INFO: Matched route "login_check" (parameters: "_controller": "null", "_route": "login_check") [] []
    [2015-02-18 17:15:25] myapp.DEBUG: Database query prepared {"statement":"SELECT `id`, `displayName`, `email`, `passwordHash`, `passwordSalt` FROM `user` WHERE `email` = ?"} []
    [2015-02-18 17:15:25] myapp.INFO: Database query complete {"statement":"SELECT `id`, `displayName`, `email`, `passwordHash`, `passwordSalt` FROM `user` WHERE `email` = ?","parameters":["user@example.com"],"time":0.00035715103149414} []
    [2015-02-18 17:15:25] myapp.INFO: User "user@example.com" has been authenticated successfully [] []
    [2015-02-18 17:15:25] myapp.INFO: < 302 http://localhost:8080/ [] []
    [2015-02-18 17:15:25] myapp.DEBUG: Write SecurityContext in the session [] []
    [2015-02-18 17:15:25] myapp.DEBUG: array (   0 => '.',   1 => '..',   2 => 'perf-7.map', ) [] []

    [2015-02-18 17:15:25] myapp.INFO: Matched route "GET_" (parameters: "_controller": "{}", "_route": "GET_") [] []
    [2015-02-18 17:15:25] myapp.INFO: Authentication exception occurred; redirecting to authentication entry point (A Token was not found in the SecurityContext.) [] []
    [2015-02-18 17:15:25] myapp.DEBUG: Calling Authentication entry point [] []
    [2015-02-18 17:15:25] myapp.INFO: < 302 http://localhost:8080/login [] []
    [2015-02-18 17:15:25] myapp.DEBUG: Write SecurityContext in the session [] []
    [2015-02-18 17:15:25] myapp.DEBUG: array (   0 => '.',   1 => '..',   2 => 'perf-7.map',   3 => 'sess_f0b05b304e93dbdcdef1280736263ff7', ) [] []

    [2015-02-18 17:15:25] myapp.INFO: Matched route "GET_login" (parameters: "_controller": "MyApp\Controller\LoginController::homeAction", "_route": "GET_login") [] []
    [2015-02-18 17:15:25] myapp.INFO: > GET /login [] []
    [2015-02-18 17:15:25] myapp.INFO: < 200 [] []
    [2015-02-18 17:15:25] myapp.DEBUG: array (   0 => '.',   1 => '..',   2 => 'perf-7.map',   3 => 'sess_f0b05b304e93dbdcdef1280736263ff7', ) [] []

The initial request is for the login screen. The last line is `var_export(scandir('/tmp'), true)`. As you can see, there's a session file (I'm using file based sessions, but I also get this problem with redis based sessions).

The second request is the login request. The user is successfully authenticated, and the SecurityContext is written to the session. This is where problems seem to begin. The session file is now gone, which you'd expect if the session ID was regenerated. But importantly, there are **no** session files.

On the third request, the expected SecurityContext was not found, which matches up if the session file isn't present. A new session is generated, and a session file exists at the end.

The fourth and last request is back to the login screen.

I'm using the following,

    hhvm 3.5.0
    silex/silex v1.2.3
    symfony/security v2.6.4

Also, this is my security setup,

    $app->register(new SecurityServiceProvider(), [
        'security.firewalls' => [
            'login' => [
                'pattern' => '^/login$'
            ],
            'app' => [
                'pattern' => '^.*$',
                'form' => ['login_path' => '/login', 'check_path' => '/login/check'],
                'logout' => ['logout_path' => '/logout'],
                'users' => $app->share(function ($app) {
                    return new UserProvider($app['user.repository']);
                })
            ]
        ]
    ]);

Any ideas?

**Comment by davedevelopment** [comment] 2015-02-18 21:15
@stephenmelrose tried throwing a $app['session']->save() in before your debug logging the `scandir`? Just wanted to rule out the session not being written by then?

**Comment by stephenmelrose** [comment] 2015-02-18 22:20
@davedevelopment I didn't, no. Nuked the hacking I'd done. I'll give it another go tomorrow.

**Comment by digitalkaoz** [comment] 2015-03-06 10:46
same problem here but with symfony and hhvm3.5.

i can confirm that PDO fixed it for me. it neither worked with snc-redis or file :/

**Comment by vguardiola** [comment] 2015-04-13 11:28
The same problem tested with HHVM 3.5 and 3.6.1, my session configuration is with the redis handler.

I test to do a session_start on app.php before kernel start and it works properly, I think is a symfony problem or a bad session configuration

I see that exist some difference between session on php and hhvm when the browser load registration/confirmed/
PHP:
```
array (size=3)
  '_sf2_attributes' => &
    array (size=1)
      '_security_mainreg' => string 'C:74:"Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken":707:... (length=795)
  '_sf2_flashes' => &
    array (size=0)
      empty
  '_sf2_meta' => &
    array (size=3)
      'u' => int 1428919484
      'c' => int 1428919484
      'l' => string '0' (length=1)
```
HHVM:
```
Array
(
    [_sf2_attributes] => Array
        (
        )
    [_sf2_flashes] => Array
        (
        )
    [_sf2_meta] => Array
        (
            [u] => 1428920356
            [c] => 1428920356
            [l] => 0
        )
)
```
I follow the code and stop (die) it when ContextListener save the token to the session and it work properly an in my redis the session is correct.

Some idea?

**Comment by wojtas** [comment] 2015-06-11 11:24
Same problem here with HHVM 3.7.1 and Symfony 2.3.28. File session storage doesn't work with HHVM and Symfony2, although in my legacy app admin panel, where I handle sessions by myself, everything is handled correctly. So it seems to be related to the session persistence implementation in Symfonyas @vguardiola suggests, rather than a general HHVM bug, or so I think. 

When I have some more time I'll try to delve into the problem.

**Comment by StyxOfDynamite** [comment] 2015-06-24 12:53
http://labs.qandidate.com/blog/2013/10/21/running-symfony-standard-on-hhvm/

Suggests the issues is with symfony2 on HHVM.

**Comment by maurocolella** [comment] 2015-06-24 13:48
There is no "suggesting".

The same core code functions differently on HHVM and PHP. The only thing to
add to this bug report is a test case, as opposed to needless static.

**Comment by MblKiTA** [comment] 2015-07-18 08:15
hhvm 3.8.0 fixed this issue for me

**Comment by fabpot** [comment] 2015-07-18 12:48
@MblKiTA Thanks for the feedback, that's very interesting. Were you able to spot from the changelog which change(s) make this work on 3.8.0?

**Comment by MblKiTA** [comment] 2015-07-19 21:38
@fabpot no, I just checked that authentication works with hhvm 3.8.0 and session file is created with user data in it:
```
_sf2_attributes|a:1:{s:15:"_security_admin";s:941:"C:74:"Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken":853:{a:3:{i:0;N;i:1;s:5:"admin";i:2;s:812:"a:4:{i:0;O:41:"Symfony\Component\Security\Core\User\User":7:{s:51:"^@Symfony\Component\Security\Core\User\User^@username";s:5:"admin";s:51:"^@Symfony\Component\Security\Core\User\User^@password";s:88:"5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg==";s:50:"^@Symfony\Component\Security\Core\User\User^@enabled";b:1;s:60:"^@Symfony\Component\Security\Core\User\User^@accountNonExpired";b:1;s:64:"^@Symfony\Component\Security\Core\User\User^@credentialsNonExpired";b:1;s:59:"^@Symfony\Component\Security\Core\User\User^@accountNonLocked";b:1;s:48:"^@Symfony\Component\Security\Core\User\User^@roles";a:1:{i:0;s:10:"ROLE_ADMIN";}}i:1;b:1;i:2;a:1:{i:0;O:41:"Symfony\Component\Security\Core\Role\Role":1:{s:47:"^@Symfony\Component\Security\Core\Role\Role^@role";s:10:"ROLE_ADMIN";}}i:3;a:0:{}}";}}";}_sf2_flashes|a:0:{}_sf2_meta|a:3:{s:1:"u";i:1437340297;s:1:"c";i:1437340297;s:1:"l";s:1:"0";}
```

**Comment by digitalkaoz** [comment] 2015-07-20 07:22
for me this fixed it: https://github.com/snc/SncRedisBundle/commit/6d513735ec0465013ec51b191e21894f057eb683

**Comment by fabpot** [comment] 2015-08-03 14:23
Closing as it apparently works for HHVM 3.8 and the redis bundle was also fixed.

**Closed by fabpot** 2015-08-03 14:23 UTC
