### ISSUE TITLE
Class 'Symfony\Bridge\Twig\Extension\HttpKernelRuntime' not found

### ISSUE THREAD

**Issue by eman1986** [silexphp/Silex#1448] opened 2016-11-15 01:02 UTC
I recently updated my copy of silex, twig, and twig bridge and looks like silex is now broken with a change to the twig bridge:

> Class 'Symfony\Bridge\Twig\Extension\HttpKernelRuntime' not found

**Comment by eman1986** [comment] 2016-11-15 23:42
reverting to 2.0.3 resolved the issue for me, so 2.0.4 has an issue

**Comment by f3ath** [comment] 2016-11-18 07:46
Can confirm this. The class is referred from here https://github.com/silexphp/Silex/blob/v2.0.4/src/Silex/Provider/TwigServiceProvider.php#L28, but it does not present here https://github.com/symfony/twig-bridge/tree/v3.1.6/Extension.

**Comment by SpacePossum** [comment] 2016-11-18 08:55
possible duplicate of https://github.com/silexphp/Silex/pull/1449 ?

**Comment by danielmartincmp** [comment] 2017-09-29 16:22
Any fix on this issue?

**Comment by hkdobrev** [comment] 2018-02-25 16:45
I've tried to fix that in #1612.

**Closed** 2018-02-26 04:56 UTC
